export * from './store'
export * from './modules/rootReducer'
export * as actionCreators from './modules/termostato/action-creators'
export * as themeActionCreators from './modules/theme/action-creators'
export * as pokemonActionCreators from './modules/pokemon/action-creators'